### ISSUE TITLE
Separate secrets from configuration files

### ISSUE THREAD

**Issue by jmcanterafonseca-iota** [gohornet/hornet#1214]
**Is your feature request related to a problem? Please describe.**
Currently there are secrets such as those related to the dashboard or the JWT that are within the  `config.json` file. It would be good that they could be separated so that they can be mapped more easily to Kubernetes Secrets for instance. One option could be to allow secrets to be read by Hornet from an environment variable. 

**Describe the solution you'd like**
If those secrets can be read from an environment variable that would be great. 
**Describe alternatives you've considered**
Separate files. 
**Additional context**
We want to improve Hornet deployments so that are more robust in production-ready environments based on Kubernetes.

**Comment by muXxer** [comment]
All settings in the config can be read from an environment variable.
In your case that would be for example:

```
DASHBOARD_AUTH_USERNAME
DASHBOARD_AUTH_PASSWORDHASH
DASHBOARD_AUTH_PASSWORDSALT
```
