### ISSUE TITLE
Failed to add event

### ISSUE THREAD

**Issue by Travetown** [gohornet/hornet#1245]
I have 3 Hornet nodes.  The entry of the events worked for two nodes.  This error appears at the 3rd node.  All nodes are configured the same and installed via apt.

![image](https://user-images.githubusercontent.com/66588710/146963836-bb3d3cbd-9138-40d9-b891-3dec3ee3f5d5.png)

**Comment by alexsporn** [comment]
Please see what happens in the Browser Javascript console

**Comment by Travetown** [comment]
<img width="830" alt="Bildschirmfoto 2021-12-21 um 17 48 56" src="https://user-images.githubusercontent.com/66588710/146967705-cfdcc618-8463-46d0-8105-3850492616f9.png">

**Comment by alexsporn** [comment]
Ok, it is an issue with your reverse proxy setup. You are exposing both the dashboard and the API over the same port (443).
So the problem is, that your API is JWT protected but exposing the same endpoints the dashboard is proxying to access the plugin API.

**Comment by alexsporn** [comment]
I would recommend exposing the API and the Dashboard using 2 different URLs, or even just different subdomains (e.g. api-iota-node.trave-tangle.de and dashboard-iota-node.trave-tangle.de)

**Comment by Travetown** [comment]
Hmmm, can I remove JWT?

**Comment by alexsporn** [comment]
> Hmmm, can I remove JWT?

then anyone can remove the events from your node ;-)

**Comment by Travetown** [comment]
I also turned on JWT stupidly.  Can I really not turn it off again on the VPS? 😩

**Comment by muXxer** [comment]
It's always on now, it's just about public routes and protected routes.
You should not mess around with this, otherwise anyone can break your node.

**Comment by Travetown** [comment]
OK.  I wonder why I didn't have the same problem on my other two nodes.  Then I leave it that way.
