### ISSUE TITLE
Dashboard does not load with version 1.1.1

### ISSUE THREAD

**Issue by Travetown** [gohornet/hornet#1250]
After the update to 1.1.1, the dashboard no longer loads with the two browsers Brave and Safari

<img width="990" alt="Bildschirmfoto 2021-12-22 um 11 58 39" src="https://user-images.githubusercontent.com/66588710/147082536-3e4c9687-7b9c-41d3-a7be-234bd33e6916.png">

Switch between the two views

<img width="625" alt="Bildschirmfoto 2021-12-22 um 12 04 57" src="https://user-images.githubusercontent.com/66588710/147083260-c7b23303-29c6-46dc-8fea-cc1119351e90.png">

**Comment by alexsporn** [comment]
Please look at the Javascript Console and report errors

**Comment by Travetown** [comment]
<img width="826" alt="Bildschirmfoto 2021-12-22 um 12 07 36" src="https://user-images.githubusercontent.com/66588710/147083505-ee6c9bd1-0e0d-4ee1-b15e-0c37ab3bd699.png">

**Comment by alexsporn** [comment]
That error is normal, it's the check for the spammer plugin. Anything else? Try logging out and back in.

**Comment by Travetown** [comment]
The spammer plugin is not activated. Logging out and in again does not bring any improvement.

This is also reported by others in Discord  (#Hornet).

**Comment by alexsporn** [comment]
Fixed with #1251
