### ISSUE TITLE
auto initiated graceful shutdown - participation plugin critical error

### ISSUE THREAD

**Issue by QNODE-CA** [gohornet/hornet#1259]
**Describe the bug**
node initiated graceful shutdown a few minutes after restarting (with milestone synced)

**To Reproduce**
- node running participation plugin with no issues, until config issue happened overnight
- in them morning, the node was updated to ver. 1.1.3 and restarted
- node was syncing slowly (~400 milestones / hr)
- node was shutdown, participation plugin was removed from config, and the node restarted
- hornet synced in about 2 minutes
- re-enabled participation plugin and restarted
- node auto shutdown after a few minutes with the following warning: `WARN	Graceful Shutdown	Node self-shutdown: participation plugin hit a critical error while applying spent TXO: current staked amount invalid; waiting (max 300 seconds) to finish processing ...`
- shutdown completed successfully

**Expected behavior**
node to continue to sync

**Environment information:**
 - OS: [e.g. Ubuntu 20.04]
 - RAM: 24 GB
 - Cores: 30 Cores
 - Type: Dell R620 (ESXi VM)
 - HORNET version 1.1.3  1d93f0b7

**Additional context**
another node of mine with the same config / build was left syncing without disabling the participation plugin and synced without issue

[screenlog.zip](https://github.com/gohornet/hornet/files/7790971/screenlog.zip)

**Comment by muXxer** [comment]
How did you install it? Do you use swarm?

**Comment by QNODE-CA** [comment]
no, built from source, go1.17.5

**Comment by muXxer** [comment]
Do you have more logs maybe?
And can you provide a full stack trace while it tries to shut down?

**Comment by QNODE-CA** [comment]
I think that the log attached goes from starting the node to completed shutdown, not sure what else to include.  I'll try and see if I can reproduce this (currently node is running without the participation plugin).  I did save the `/mainnet/participation` folder before restarting though, maybe that can be of use?

**Comment by muXxer** [comment]
Ahhhh sorry, I didn't see the log. I'm on vacation for the next weeks, so I won't be able to have a look :)
But I guess a full stack trace would help the most.
In the hornet channel on discord there is a pinned message how you can create one. 
It must be created in the moment the node is stuck during shutdown.

**Comment by QNODE-CA** [comment]
np. I'll re-enable the plugin and try that, probably sometimes tomorrow

**Comment by muXxer** [comment]
Thank you very much! :)

**Comment by QNODE-CA** [comment]
- stopped node
- restored participation db (I had saved the participation folder after the 1st crash)
- enabled participation plugin and started node
- node shutdown with the same error after 13 minutes - unfortunately I did not manage to capture the trace :-(
- repeated the process several times, and the node has not shutdown - node has been up overnight running participation (8-9 hours) and is still running fine

**Comment by alexsporn** [comment]
You should not mix up participation databases and utxo/tangle databases. The whole mainnetdb folder needs to be seen as one entity that needs to match internally.
