### ISSUE TITLE
windows build failure

### ISSUE THREAD

**Issue by MasterDimmy** [gohornet/hornet#1264]
**Describe the bug**
Windows build failed.

**To Reproduce**
go build -tags rocksdb

**Expected behavior**
build success

**Environment information:**
 - OS: Windows 17
 - RAM: 96GB
 - Cores: 32
 - Type: PC x64
 - Browser : -
 - HORNET : code snapshot at https://github.com/gohornet/hornet/commit/0a901038feb7aeca4bd8b15d83e08067c414a77c 

**Additional context**
D:\Projects\hornet>go build -tags rocksdb
go: downloading github.com/gohornet/grocksdb v1.6.38-0.20211012114404-55f425442260
go: downloading github.com/stretchr/testify v1.7.1-0.20210427113832-6241f9ab9942
# github.com/linxGnu/grocksdb
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ldl
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lzstd
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -llz4
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lz
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lsnappy
collect2.exe: error: ld returned 1 exit status

Choose another DB! LevelDB, etc.

**Comment by alexsporn** [comment]
You need to have RocksDB and all the libs available in your build environment if you want to build on Windows.
