### ISSUE TITLE
compile error Hornet 1.1.3 Go 1.17 RPI OS

### ISSUE THREAD

**Issue by jdbadams** [gohornet/hornet#1265]
Compiling 1.1.3 using appropriate Go version produces

fatal error: rocksdb/c.h: No such file or directory
 // #include "rocksdb/c.h"

./scripts/build_hornet_rocksdb_builtin.sh 

go version
go version go1.17.5 linux/arm

uname -a
Linux mobilecomputer 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux

apt-get update/upgrade ran before compile

**Comment by alexsporn** [comment]
We do not support 32bit architectures. Switch to an arm64 distribution.
