### ISSUE TITLE
Using CLI tools without a config.json causes warnings

### ISSUE THREAD

**Issue by rajivshah3** [gohornet/hornet#1267]
**Describe the bug**
If we want to use the CLI for an operation such as getting the details of a snapshot (`hornet tools snap-info`) and do not have a `config.json` in the directory, warnings appear:

```
No config file found via 'config.json'. Loading default settings.No peering config file found via 'peering.json'. Loading default settings.No profiles config file found via 'profiles.json'. Loading default settings.
```

**To Reproduce**
1. Download a snapshot (from https://chrysalis-dbfiles.iota.org/snapshots/hornet/latest-full_snapshot.bin, for example)
2. Run `hornet tools snap-info latest-full_snapshot.bin`

**Expected behavior**
The warnings should not appear for tools that don't seem to need a `config.json` or `peering.json`

**Environment information:**
 - OS: macOS 12.1, also happens on Ubuntu
 - HORNET version: 1.1.3

**Comment by muXxer** [comment]
Should be fixed with #1300
