### ISSUE TITLE
systemd: hornet service is killed after 1w

### ISSUE THREAD

**Issue by miili** [gohornet/hornet#1278]
**Describe the bug**
Hornet service runs out of memory after 1 week and is killed.
Subsequently the database is corrupted and the hornet cannot start.

**Expected behavior**
Stable operation for months.

**Environment information:**
 - OS: Debian 11
 - **RAM: 2 GB**
 - Cores: 1 Core
 - Type: VPS
 - HORNET version 1.1.3

```
Jan 05 20:35:59 iota-hornet hornet[1118132]: req(qu/pe/proc/lat): 00001/00005/00000/0000ms, reqQMs: 2171742, processor: 00000, CMI/LMI: 2171689/2171741, MPS (in/new/out): 00031/00000/00000, Tips (non-/semi-lazy): 20/0
Jan 05 20:35:59 iota-hornet hornet[1118132]: req(qu/pe/proc/lat): 00000/00006/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 2171689/2171741, MPS (in/new/out): 00031/00000/00000, Tips (non-/semi-lazy): 20/0
Jan 05 20:36:03 iota-hornet hornet[1118132]: req(qu/pe/proc/lat): 00000/00006/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 2171689/2171741, MPS (in/new/out): 00031/00000/00000, Tips (non-/semi-lazy): 20/0
Jan 05 20:36:03 iota-hornet hornet[1118132]: req(qu/pe/proc/lat): 00000/00006/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 2171689/2171741, MPS (in/new/out): 00031/00000/00000, Tips (non-/semi-lazy): 20/0
Jan 05 20:36:06 iota-hornet hornet[1118132]: 2022-01-05T20:36:06+01:00        INFO        WarpSync        Checkpoint updated to milestone 2171743 (target 2171743)
Jan 05 20:36:16 iota-hornet hornet[1118132]: req(qu/pe/proc/lat): 00006/00000/00000/0000ms, reqQMs: 2171742, processor: 00000, CMI/LMI: 2171689/2171741, MPS (in/new/out): 00031/00000/00000, Tips (non-/semi-lazy): 20/0
Jan 05 20:36:17 iota-hornet hornet[1118132]: req(qu/pe/proc/lat): 00005/00001/00000/0000ms, reqQMs: 2171741, processor: 00000, CMI/LMI: 2171689/2171741, MPS (in/new/out): 00031/00000/00000, Tips (non-/semi-lazy): 20/0
Jan 05 20:36:22 iota-hornet hornet[1118132]: req(qu/pe/proc/lat): 00004/00002/00000/0000ms, reqQMs: 2171742, processor: 00000, CMI/LMI: 2171689/2171741, MPS (in/new/out): 00031/00000/00000, Tips (non-/semi-lazy): 20/0
Jan 05 20:36:28 iota-hornet systemd[1]: hornet.service: A process of this unit has been killed by the OOM killer.
Jan 05 20:36:28 iota-hornet systemd[1]: hornet.service: Main process exited, code=killed, status=9/KILL
Jan 05 20:36:28 iota-hornet systemd[1]: hornet.service: Failed with result 'oom-kill'.
Jan 05 20:36:28 iota-hornet systemd[1]: hornet.service: Consumed 1w 1h 13min 48.387s CPU time.
Jan 05 20:36:29 iota-hornet systemd[1]: hornet.service: Scheduled restart job, restart counter is at 1.
Jan 05 20:36:29 iota-hornet systemd[1]: Stopped HORNET.
Jan 05 20:36:29 iota-hornet systemd[1]: hornet.service: Consumed 1w 1h 13min 48.387s CPU time.
```

**Comment by alexsporn** [comment]
Are you running default config?
Apt installation or any 3rd-party tool?
What else is running on that server?

**Comment by miili** [comment]
> Are you running default config?

Yes.
* Added login information.
* Changed `pruning.size.target = 10 GB`
* Added `participation` plugin

> Apt installation or any 3rd-party tool?

deb installed through apt

> What else is running on that server?

Nothing

For now I bumped the log level to DEBUG and will wait until it happens again.

**Comment by muXxer** [comment]
![grafik](https://user-images.githubusercontent.com/32371094/149751837-43f77b0a-b99a-4bfa-afdf-1c0219dd2b66.png)
this is our mainnet node, no problems so far :shrug:

**Comment by miili** [comment]
Please leave this issue open until the behavior is reproduced.

**Comment by Dr-Electron** [comment]
You are running on a hardware way bellow the recommended spec. I think we can close this

**Comment by miili** [comment]
> You are running on a hardware way bellow the recommended spec. I think we can close this

Let's document what is happening. I will close the issue once reproduced with verbose logging.
It appears like the memory consumption is not increasing gradually but jumping.

**Comment by miili** [comment]
The node is now up since 2w and running stable. Without the `participation` plugin enabled. Could that have been consuming the memory?

**Comment by miili** [comment]
Still running (18d). Could the participation plugin have consumed all the memory?

**Comment by muXxer** [comment]
I guess your setup was just to slow to keep up with the participation plugin enabled.
We are currently working on a new version of hornet, that should reduce the load generated by the participation heavily.

**Comment by alexsporn** [comment]
We fixed memory leaks and optimized participation in the upcoming 1.2.0 release
