### ISSUE TITLE
Needs for JSON output and write on file parameter in p2pidentity-gen and ed25519-key tools

### ISSUE THREAD

**Issue by mastrogiovanni** [gohornet/hornet#1287]
**Is your feature request related to a problem? Please describe.**
I need to generate programmatically keys and p2p identities in a containerized environment.
It's difficult to me automatize the script required to produce such values.
 
**Describe the solution you'd like**
I would like to add some `--json` parameter to output the result of (at least) `p2pidentity-gen` and `ed25519-key` tools to produce JSON output.
Moreover I would like to have a `--output file.json`, `-o file.json` to save the result on file instead printing on standard output

**Describe alternatives you've considered**

**Additional context**

**Comment by alexsporn** [comment]
`hornet tools ed25519-key --json` already works.
How would you like the output of the `p2pidentity-gen` tool?

**Comment by mastrogiovanni** [comment]
--json for p2pidentity-get would be nice, you could use also same names for keys (even if are long).
Important also is to have a command parameter to output on file instead of standard output.
This simplify the life in Kubernetes

**Comment by alexsporn** [comment]
Why don't you use the identity file that is generated?

**Comment by mastrogiovanni** [comment]
Sorry, I didn't know. Can you specify me in what location is created and what's the name of the file?

**Comment by alexsporn** [comment]
Added with #1289
