### ISSUE TITLE
Update wiki docs for toolset clean up

### ISSUE THREAD

**Issue by Dr-Electron** [gohornet/hornet#1303]
**Describe the bug**

The docs need to be updated to reflect this changes: https://github.com/gohornet/hornet/commit/62b7460184b1cb820e2a643513f3b286961db8e9

I may have time over the weekend to look at it

**Comment by Dr-Electron** [comment]
I'm working on it and will fix it over the next days depending on when I have time.
But first I need to find out again what the problem was :trollface: 
I guess I should make the changes on `develop` and you will add it to `mainnet` too. Or should I create PRs for both?

**Comment by muXxer** [comment]
If it affects both, then please create both PRs.

**Comment by Dr-Electron** [comment]
Ok I remember now why I opened this issue 😅 
I found some issues with the private tangle docs and then wanted to look at all tools in general.
But everything was already fixed with https://github.com/iotaledger/hornet/pull/1310. I just checked the docs anyway, but all tools seem to be up-to-date.
Will close the issue :)
