### ISSUE TITLE
delta_snapshot.bin not found 

### ISSUE THREAD

**Issue by kubrt-d** [gohornet/hornet#1305]
The default 

https://cdn.tanglebay.com/snapshots/mainnet/delta_snapshot.bin

gives 404

**Comment by muXxer** [comment]
And how is that a problem for you? :)
Tanglebay decided to create new full_snapshot files everytime. They don't ship the delta, because they don't need.
But it's no problem for hornet if the delta is not there.

**Comment by kubrt-d** [comment]
Not a problem, just FYI. Hornet tries and fails to download this file every time during startup.

**Comment by muXxer** [comment]
Thx!
