### ISSUE TITLE
/bin/ash might not be correct?

### ISSUE THREAD

**Issue by centercirclesolutions** [gohornet/hornet#1387]
https://github.com/gohornet/hornet/blob/bd611bc74b4171aa13d7a86970ad07380c8fee9d/private_tangle/docker-compose.yml#L9

**Comment by alexsporn** [comment]
Yes it is ;-)
It runs inside alpine linux and that is a built-in shell there.

**Comment by centercirclesolutions** [comment]
I knew it was going to be something like that, learned something new today
