### ISSUE TITLE
Unable to deploy the private tangle on Ubuntu

### ISSUE THREAD

**Issue by oopsmonk** [gohornet/hornet#1389]
**Describe the bug**

Got snapshots creation error and permission denied when trying to deploy private tangle on Ubuntu 20.04. 

**To Reproduce**
- clone hornet and checkout v2.0.0-alpha6
- goto `private_tangle` folder
- run `./bootstrap.sh`

**Expected behavior**

The `./bootstrap.sh` should spin up a private tangle on local PC without problems.

**Environment information:**
 - OS: Ubuntu 20.04
 - docker version 19.03.13
 - Docker Compose version v2.3.4
 - HORNET version v2.0.0-alpha6

**Additional context**

```
[+] Running 0/1
 ⠿ create-snapshots Error
[+] Building 261.4s (21/21) FINISHED
...
error: unable to create snapshot file: open /app/snapshots/coo/full_snapshot.bin_tmp: permission denied
...
2022-03-31T15:00:40Z    PANIC   Database        could not create database dir 'privatedb/tangle': mkdir privatedb/tangle: permission denied
github.com/gohornet/hornet/pkg/node.(*Pluggable).LogPanic
```

**Comment by oopsmonk** [comment]
error logs using `fix/private-tangle-permissions` https://github.com/gohornet/hornet/commit/9e51b0b9460d3a395d51660090ee222dcafaf37b

```
$ sudo ./bootstrap.sh
[+] Building 134.3s (21/21) FINISHED
 => [internal] load build definition from Dockerfile
 => => transferring dockerfile: 32B
 => [internal] load .dockerignore
 => => naming to docker.io/library/hornet:dev
 ...
WARN[0000] Found orphan containers ([private_tangle-prepare_files-1 private_tangle-cleanup-1]) for this project. If you removed or renamed this service in your compose file,
 you can run this command with the --remove-orphans flag to clean it up
error: unable to create snapshot file: open /app/snapshots/coo/full_snapshot.bin_tmp: no such file or directory
cp: cannot stat 'snapshots/coo': No such file or directory
cp: cannot stat 'snapshots/coo': No such file or directory
cp: cannot stat 'snapshots/coo': No such file or directory
WARN[0000] Found orphan containers ([private_tangle-prepare_files-1 private_tangle-cleanup-1]) for this project. If you removed or renamed this service in your compose file,
 you can run this command with the --remove-orphans flag to clean it up.
...
2022-04-01T06:13:09Z    PANIC   Database        could not create database dir 'privatedb/tangle': mkdir privatedb/tangle: permission denied
github.com/gohornet/hornet/pkg/node.(*Pluggable).LogPanic
        /scratch/pkg/node/plugin.go:126
...
main.main
        /scratch/main.go:35
runtime.main
        /usr/local/go/src/runtime/proc.go:250
panic: could not create database dir 'privatedb/tangle': mkdir privatedb/tangle: permission denied
```

**Comment by muXxer** [comment]
@oopsmonk did you try the latest develop branch? https://github.com/gohornet/hornet/commit/2ce5dc15c1910826c6d81befc6f61b2d8e6bc92d

Should be fixed there.

**Comment by oopsmonk** [comment]
> @oopsmonk did you try the latest develop branch? [2ce5dc1](https://github.com/gohornet/hornet/commit/2ce5dc15c1910826c6d81befc6f61b2d8e6bc92d)
> 
> Should be fixed there.

permission issues are fixed and node is running but cannot access the network, including API, Faucet, Dashboard

```
$ curl -v http://localhost:14265/api/v2/info
*   Trying 127.0.0.1:14265...
* TCP_NODELAY set
* connect to 127.0.0.1 port 14265 failed: Connection refused
* Failed to connect to localhost port 14265: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 14265: Connection refused

$ curl -v http://localhost:8081
*   Trying 127.0.0.1:8081...
* TCP_NODELAY set
* connect to 127.0.0.1 port 8081 failed: Connection refused
* Failed to connect to localhost port 8081: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 8081: Connection refused

$ curl -v http://localhost:8091
*   Trying 127.0.0.1:8091...
* TCP_NODELAY set
* connect to 127.0.0.1 port 8091 failed: Connection refused
* Failed to connect to localhost port 8091: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 8091: Connection refused
```

**Comment by mahermeg17** [comment]
Hi,

Using the latest commit 2ce5dc1

```
hornet/private_tangle$ sudo ./bootstrap.sh 
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.coo-bootstrap: 'profiles'
Unsupported config option for services.create-snapshots: 'profiles'
Unsupported config option for services.hornet-3: 'profiles'
Unsupported config option for services.hornet-4: 'profiles'
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.coo-bootstrap: 'profiles'
Unsupported config option for services.create-snapshots: 'profiles'
Unsupported config option for services.hornet-3: 'profiles'
Unsupported config option for services.hornet-4: 'profiles'
```
Any idea about this issue?
Thanks in advance.

**Comment by alexsporn** [comment]
You need to have docker-compose >= 1.28.0

**Comment by mahermeg17** [comment]
Thank you alexsporn! I was using 1.27.

**Comment by oopsmonk** [comment]
tried the latest commit https://github.com/gohornet/hornet/commit/e2e7a53c7bd23c71dcddc225f65f4376a545148c

```
$ sudo ./bootstrap.sh 
[+] Running 0/0
 ⠿ Network private_tangle_peering_net  Error                                                                                                                            0.0s
failed to create network private_tangle_peering_net: Error response from daemon: Pool overlaps with other one on this address space
[+] Running 0/0
 ⠿ Network private_tangle_peering_net  Error                                                                                                                            0.0s
failed to create network private_tangle_peering_net: Error response from daemon: Pool overlaps with other one on this address space
```

**Comment by muXxer** [comment]
@oopsmonk thats some problem on your machine, not related to our docker config.

That error suggest a conflict. You could list the network `docker network ls` and delete the overlapping ones `docker network rm my_network`.

**Comment by oopsmonk** [comment]
> @oopsmonk thats some problem on your machine, not related to our docker config.
> 
> That error suggest a conflict. You could list the network `docker network ls` and delete the overlapping ones `docker network rm my_network`.

thanks @muXxer, the network was created by `bootstrap.sh`, called `private_tangle_default`.
the node is up and running after removing the network, but I still unable to get responses from API endpoints, the same errors that were described in https://github.com/gohornet/hornet/issues/1389#issuecomment-1088855239
the new script creates two networks which are `private_tangle_default` and  `private_tangle_peering_net`. is anything missing?

**Comment by alexsporn** [comment]
`private_tangle_default` should not be created anymore, I commited a fix for that

**Comment by muXxer** [comment]
@oopsmonk I'm sure that is a problem on your side. Your user can't access docker.
Did you follow the docker post install guide closely? you need to add your user to the docker group.

https://docs.docker.com/engine/install/linux-postinstall/

**Comment by oopsmonk** [comment]
> @oopsmonk I'm sure that is a problem on your side. Your user can't access docker. Did you follow the docker post install guide closely? you need to add your user to the docker group.
> 
> https://docs.docker.com/engine/install/linux-postinstall/

the user is in docker group. 
```
$ groups 
sam adm dialout cdrom sudo dip plugdev lpadmin sambashare vboxusers wireshark docker
```
my system has run some docker containers without problems, no other containers were running when testing hornet.

**Comment by oopsmonk** [comment]
following a simple example to check my system, here https://github.com/chentex/go-rest-api

I didn't get any problems
```
$ git clone https://github.com/chentex/go-rest-api.git
$ cd go-rest-api/
$ docker build -f Dockerfile . -t gorestapi:latest 
$ docker run --rm -p 8080:8080 gorestapi:latest
$ curl http://localhost:8080/test
{"color":"yellow","message":"This is a Test","notify":"false","message_format":"text"}
```
even I changed the port to 14265
```
$ docker run --rm -p 14265:8080 gorestapi:latest
$ curl http://localhost:14265/test
{"color":"yellow","message":"This is a Test","notify":"false","message_format":"text"}
```

**Comment by muXxer** [comment]
Which docker version are you using?
Which docker-compose version are you using?

**Comment by oopsmonk** [comment]
> Which docker version are you using? Which docker-compose version are you using?

please refer to **Environment information** in the issue description.

**Comment by muXxer** [comment]
```
docker-compose --version
docker-compose version 1.29.2, build 5becea4c
```
```
docker --version
Docker version 20.10.7, build 20.10.7-0ubuntu5.1
```
For me, these builds work with the current code :shrug:

**Comment by oopsmonk** [comment]
> ```
> docker-compose --version
> docker-compose version 1.29.2, build 5becea4c
> ```
> 
> ```
> docker --version
> Docker version 20.10.7, build 20.10.7-0ubuntu5.1
> ```
> 
> For me, these builds work with the current code shrug

that's odd, so I looked into the docker-compose.yml script.
all services are running under a subnet with static IPs and I can access the dashboard and API endpoints via 172.18.211.11 instead of localhost.

```
$ curl http://172.18.211.11:14265/api/v2/info
{"name":"HORNET","version":"2.0.0-alpha7","status":{"isHealthy":false,"latestMilestoneTimestamp":1649690858,"latestMilestoneIndex":31,"confirmedMilestoneIndex":31,"pruningIndex":0},"metrics":{"messagesPerSecond":0.1,"referencedMessagesPerSecond":0.1,"referencedRate":100},"protocol":{"networkName":"private_tangle1","protocolVersion":2,"bech32HRP":"atoi","minPoWScore":1,"rentStructure":{"vByteCost":500,"vByteFactorData":1,"vByteFactorKey":10}},"features":["PoW"],"plugins":[]}
```

you might do some configuration manually?

**Comment by muXxer** [comment]
No, we just spawn with the scripts.
The IPs are fixed in the docker-compose file, but it works with localhost without problems for me.
I guess that's a docker problem due to the horrible old version you use.

**Comment by oopsmonk** [comment]
problem solved. the old docker version is okay but I should update it as well, thanks.

the expectation is false in the issue description. 
```
Expected behavior

The ./bootstrap.sh should spin up a private tangle on local PC without problems.
```

the `bootstrap.sh` just creates initial snapshot and required files, `run.sh` is needed to spin up a full network(coo+node).
In previous releases,  deploying private Tangle just need to run `run_coo_bootstrap.sh`
