### ISSUE TITLE
Private Tangle NodeError : Couldn't get a result from any node

### ISSUE THREAD

**Issue by mahermeg17** [gohornet/hornet#1396]
**Describe the bug**
Can't connect local node using nodejs client.

**To Reproduce**
- clone [2ce5dc1](https://github.com/gohornet/hornet/commit/2ce5dc15c1910826c6d81befc6f61b2d8e6bc92d)
- cd private_tangle.
- run ./bootstrap.sh
- run ./run.sh
- run nodejs client

```
const { ClientBuilder } = require('@iota/client')
function run() {
    const { ClientBuilder } = require('@iota/client');
    const client = new ClientBuilder()
        .node('http://localhost:14265')
        .build();
    client.getInfo().then(console.log).catch(console.error);
}
run()
```

**Expected behavior**
Get node info

**Environment information:**
 - OS: [Ubuntu 18.04]
 - RAM: [16 GB]
 - Cores: [12 Cores]
 - Type: [laptop]
 - Browser [brave]
 - HORNET version [v2.0.0-alpha6]

**Additional context**
1. node client error

```
[Error: ClientTask error: Client(NodeError("Couldn't get a result from any node"))]
```
2. http://localhost:14265/

```
{
error: {
code: "403",
message: "Forbidden, error: code=403, message=Forbidden"
}
}
```
3. http://localhost:8081/

```
{
message: "remote http://127.0.0.1:9090 unreachable, could not forward: dial tcp 127.0.0.1:9090: connect: connection refused"
}
```

Any idea about the origin of this bug?
Thank you.

**Comment by muXxer** [comment]
Port 9090 ? Thats weird.
Did you activate the dev mode for the dashboard in the config?

```json
  "dashboard": {
    "bindAddress": "0.0.0.0:8081",
    "dev": false,
```
this must be set to false

**Comment by mahermeg17** [comment]
Thank you! I get a working dashboard now.
I make "dev" true because I couldn't connect to the node.
But I still getting the node client error : 

[Error: ClientTask error: Client(NodeError("Couldn't get a result from any node"))]

reassure me that hornet v2.0.0-alpha6 is compatible with nodejs library @iota/client 2.2.3.

I'm new whith iota. I spent a lot of time trying to setup a private tangle with the https://github.com/iotaledger/one-click-tangle.
But no success. with it I can just get node info. But no success when sending message.
So I swicth to this repo (more reactive community).

**Comment by muXxer** [comment]
Ahhh now I understand your problem :)
You are using the develop branch, which is the upcoming version of the IOTA protocol.
The client lib you use is for current mainnet version.

You need to use the "mainnet" branch instead.
The private tangle setup there is a bit different than on current develop, but it will work too.

**Comment by mahermeg17** [comment]
OK!
Thank you again.
I will checkout the mainnet branch.
