### ISSUE TITLE
Pruning doesn´t work anymore after update to 1.2

### ISSUE THREAD

**Issue by MiKeF05** [gohornet/hornet#1428]
**Describe the bug**
After the update via APT to the latest version 1.2 (IOTA mainnet) the pruning of the node doesn´t work anymore. I have tried it with "db size" and "milestone based" pruning. The node currently has about 68Gb (image 1) and the pruning setting is set to 60Gb. At the startup of the node the correct config.json file is loaded with the setting of db size pruning and 60Gb (image 2).

With the update to 1.2 I replaced the config.json and adapted the values back to the previous ones. The following values were changed:
- dashboard.bindAddress
- dashboard.auth.username
- dashboard.auth.passwordHash
- dashboard.auth.passwordSalt
- pruning.size.targetsize
- node.enablePlugins

![image](https://user-images.githubusercontent.com/71659397/163803272-36a03504-0bbc-4d84-a406-3a938ef31c30.png)
(image 1)

![image](https://user-images.githubusercontent.com/71659397/163803365-5450e401-2109-4ef8-9d7a-29d7ce0c73b1.png)
(image 2)

**To Reproduce**
- Set the targetSize in config.json to a value smaller than the current db size of the node

**Expected behavior**
The node should prune the data according to the settings in the config.json

**Environment information:**
- Hetzner CPX21
 - OS: Ubuntu 18.04.6 LTS
 - RAM: 4 GB
 - Cores: 3 vCPU
 - Type: VPS
 - Browser: Chrome
 - HORNET version: 1.2

**Comment by MiKeF05** [comment]
After deleting the db pruning works again.

**Comment by muXxer** [comment]
Sorry Mike, we didn't have time to look into that issue.
But good that it works for you now.

**Comment by MiKeF05** [comment]
No worries. I guess it was something on my side as nobody else had problems with pruning. So all good ;-)
