### ISSUE TITLE
Check LastMilestone logic in case Last Milestone was not detected yet (wrong pubkey etc)

### ISSUE THREAD

**Issue by muXxer** [gohornet/hornet#1436]
There is an edge case where nodes maybe don't know the correct public keys while they receive the milestone (e.g. outdated pubkeys in the config file).

When the node owner fixes the config, and restarts the node, the newly added `LastMilestone` logic should not fail.

**Comment by luca-moser** [comment]
The appropriate code seems to be already within `AddBlockToStorage` where it is checked whether given block was already stored+is a milestone+and its index hasn't been mapped yet:

https://github.com/iotaledger/hornet/blob/f1df3d1209feb6adc0d1bfeed9dbef6d2bce607f/pkg/tangle/message.go#L13-L42

**Comment by muXxer** [comment]
Validated that it works by running a node with wrong coo keys in alphanet for some time (so it receives milestones but doesn't know the keys). After fixing the config, the node synced without a problem! :+1:
