### ISSUE TITLE
Check why there is a RPC error in INX server if the last MQTT client disconnects

### ISSUE THREAD

**Issue by muXxer** [gohornet/hornet#1439]
Can this error message maybe hidden in case the INX client disconnects properly?
![grafik](https://user-images.githubusercontent.com/32371094/164465707-ab6bdd5a-8dda-4027-afcd-3b8adbe3ff6d.png)

**Comment by luca-moser** [comment]
Seems no longer relevant as the log spamming doesn't occur.
