### ISSUE TITLE
No sync in AWS

### ISSUE THREAD

**Issue by sergorl** [gohornet/hornet#1448]
**Describe the bug**
Health status and sync status are red (no sync)

**To Reproduce**
1. I opened next `tcp ports` in AWS EC2 instance: `14626, 14265, 15600`
2. Launch node using [docker](https://wiki.iota.org/hornet/getting_started/using_docker)

**Expected behavior**
Successful sync.

**Environment information:**
 - OS: [Ubuntu 20.04]
 - RAM: [8 GB]
 - Cores: [2 Cores]
 - Type: [e.g. Raspberry Pi 3B+, VPS, ...]
 - Browser [e.g. chrome, safari] (e.g. for HORNET Dashboard issues)
 - HORNET version [latest]

**Additional context**
Add any other context about the problem here [e.g. HORNET logs, errors, screenshots]

**Comment by alexsporn** [comment]
Did you peer with anyone? Autopeering is not enabled by default

**Comment by sergorl** [comment]
@alexsporn , I think no - I don't see any peers in dashboard. Here is the part of my `config.json` about autopeering:

```json
"autopeering": {
      "bindAddress": "0.0.0.0:14626",
      "entryNodes": [
        "/dns/lucamoser.ch/udp/14826/autopeering/4H6WV54tB29u8xCcEaMGQMn37LFvM1ynNpp27TTXaqNM",
        "/dns/entry-hornet-0.h.chrysalis-mainnet.iotaledger.net/udp/14626/autopeering/iotaPHdAn7eueBnXtikZMwhfPXaeGJGXDt4RBuLuGgb",
        "/dns/entry-hornet-1.h.chrysalis-mainnet.iotaledger.net/udp/14626/autopeering/iotaJJqMd5CQvv1A61coSQCYW9PNT1QKPs7xh2Qg5K2",
        "/dns/entry-0.mainnet.tanglebay.com/udp/14626/autopeering/iot4By1FD4pFLrGJ6AAe7YEeSu9RbW9xnPUmxMdQenC",
        "/dns/entry-1.mainnet.tanglebay.com/udp/14636/autopeering/CATsx21mFVvQQPXeDineGs9DDeKvoBBQdzcmR6ffCkVA"
      ],
      "entryNodesPreferIPv6": false,
      "runAsEntryNode": false
    }
```

**Comment by alexsporn** [comment]
You need to enable the Autopeering plugin. See here https://wiki.iota.org/hornet/post_installation/peering#autopeering

**Comment by sergorl** [comment]
@alexsporn , big thanks - it works like a charm ;)
