### ISSUE TITLE
The messages endpoints should have the same response if the message is not found

### ISSUE THREAD

**Issue by oopsmonk** [gohornet/hornet#1488]
**Describe the bug**

If the message is not found, the responses of messages and message metadata are identical but the response of messages children is different. Responses should be consistent in `/api/v2/messages` group.

/api/v2/messages/{messageId}
/api/v2/messages/{messageId}/metadata
```
{
  "error": {
    "code": "404",
    "message": "Not Found, error: message not found: 0xf4f0efc9babad540ee5a760f510804957799c72c62b559ed84c769245fd636ac: code=404, message=Not Found"
  }
}
```

/api/v2/messages/{messageId}/children
```
{
  "messageId": "0xf4f0efc9babad540ee5a760f510804957799c72c62b559ed84c769245fd636ac",
  "maxResults": 1000,
  "count": 0,
  "childrenMessageIds": []
}
```

**Environment information:**

 - HORNET version 2.0.0-alpha10

**Comment by alexsporn** [comment]
While I agree this behaviour does not seem consistent, this would require additional db lookups just to return 404 instead of an empty result list.
When we lookup the children of a message, we don't care about the message itself, we just iterate over our lookup tables where we store the children reference.

**Comment by oopsmonk** [comment]
`messages` endpoints should have a consistent response, either an error message or an empty list in this situation.

**Comment by oopsmonk** [comment]
> While I agree this behaviour does not seem consistent, this would require additional db lookups just to return 404 instead of an empty result list. When we lookup the children of a message, we don't care about the message itself, we just iterate over our lookup tables where we store the children reference.

this issue is about error handling and user experience of node APIs. A client can pass valid ID strings via restful APIs, it doesn't know whether the ID is a messageID, a milestoneID, or others, and all the restful routes return an error if the ID is not found in the node, except `/api/v2/messages/{messageId}/children`.
if this API is special, can the client treat the `empty list` as equal to `not found`?

**Comment by muXxer** [comment]
No you can't. 
Even if the message exists, an empty response is still valid, because there may be no children yet.
Like Alex said, if you pass a non existing message id from client side, you are already doing something wrong. It seems like a weird overhead to at that check on node side, because it would hit the efficiency of the node implementation for something that is clearly a user error.

**Comment by oopsmonk** [comment]
> No you can't. Even if the message exists, an empty response is still valid, because there may be no children yet. Like Alex said, if you pass a non existing message id from client side, you are already doing something wrong. It seems like a weird overhead to at that check on node side, because it would hit the efficiency of the node implementation for something that is clearly a user error.

yes, it's about error handlings on a wrong operation. a client application can use milestone id on message endpoints by accident or misuse. if the response is like other APIs, the client lib can throw an error and tell the application that's a wrong id. 
the question is if this situation happens how do users/developers investigate the problem? the client lib won't throw any error according to this design. how does the application know it's a misuse or a message has no children yet?
if you think this kind of situation won't happen on a client application then we can ignore and close this issue.

**Comment by muXxer** [comment]
Children endpoint was removed with #1532
