### ISSUE TITLE
Node Status does not contain `milestone_id` shortly after node startup

### ISSUE THREAD

**Issue by DaughterOfMars** [gohornet/hornet#1558]
**Describe the bug**
During a brief window after the node starts, requests to the INX `readNodeStatus` return `MilestoneInfo` without the `milestone_id` field. From `inx-chronicle`:

```
NodeStatus {
    is_healthy: false,
    latest_milestone: Some(
        Milestone {
            milestone_info: Some(
                MilestoneInfo {
                    milestone_id: None,
                    milestone_index: 420495,
                    milestone_timestamp: 0,
                },
            ),
            milestone: None,
        },
    ),
    confirmed_milestone: Some(
        Milestone {
            milestone_info: Some(
                MilestoneInfo {
                    milestone_id: None,
                    milestone_index: 420495,
                    milestone_timestamp: 0,
                },
            ),
            milestone: None,
        },
    ),
    tangle_pruning_index: 420495,
    milestones_pruning_index: 420495,
    ledger_pruning_index: 420495,
    ledger_index: 420495,
}
```

**To Reproduce**
- Start a fresh instance of hornet
- Send an INX request to `readNodeStatus`

**Expected behavior**
The `milestone_id` should be present

**Environment information:**
 - HORNET `2.0.0-alpha18`

**Comment by muXxer** [comment]
This is a legit behaviour.
The node may not know about the milestone yet, because it could also happen that there is no milestone yet after bootstrapping a new network. Same applies for the node after starting from a snapshot and a new milestone was not confirmed yet.
