### ISSUE TITLE
Add API endpoint to determine which api model is used

### ISSUE THREAD

**Issue by MOSDEV82** [gohornet/hornet#1569]
**Is your feature request related to a problem? Please describe.**
I plan to rent virtual servers to support the iota ecosystem. at this moment i just have one iota mainnet, one shimmer testnet node, and also 1x GoShimmer and 1x Wasp. 

To monitore my nodes I like to rebuild a dashboard, like tanglebays. But for now, we have two api endpoints.
Example: For Hornet 1.x: /api/v1/info and for Hornet 2.x /api/v2/info

**Describe the solution you'd like**
I simply need an endpoint like /api/version to determine is it v1 or v2
eg: /api/version returns {APILEVEL: 1} (or 2)

Thx

**Comment by alexsporn** [comment]
This is solved by #1576 
We now have a `/api/routes` endpoint that returns something like this:
```
{
  "routes": [
    "core/v2",
    "dashboard-metrics/v1",
    "indexer/v1"
  ]
}
```
The v2 api is now found under `/api/core/v2`

**Comment by alexsporn** [comment]
Note, there is currently no plan to backport this to HORNET v1.x

**Comment by MOSDEV82** [comment]
Today I had the time to check that out...
I get no access to the api... I installed Shimmer-Hornet new... But I got the following error... 

{"error":{"code":"400","message":"missing or malformed jwt, error: code=400, message=missing or malformed jwt"}}

It not depend on the API I choose... /api/core/v2, /api/routes etc...
