### ISSUE TITLE
Question: Is it possible to sync complete database among nodes?

### ISSUE THREAD

**Issue by MLStoltzenburg** [gohornet/hornet#1573]
**Describe the bug**
It's not a bug, but it's a question.

I would like to create a new node in my private tangle.
I did, but I didn't succeed in a full sync between nodes.

My question is: Is it possible to sync a new node with another node's full database or adjust the pruning index at start?

I've searched for a solution, but haven't found it.

Thank you for any help!

**Environment information:**
 - Kubernetes 1.22
 - gohornet / hornet / 1.2.1

**Additional context**
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/2595026/174669312-7c165ec3-ba38-49e8-a3b9-6932b34f2e77.png">
<img width="1106" alt="Captura de Tela 2022-06-20 às 16 54 12" src="https://user-images.githubusercontent.com/2595026/174670398-0561b7bd-97e1-4726-9e3a-e1f5c94ba186.png">

**Comment by alexsporn** [comment]
You need to use the initial full-snapshot that was used to start the network. If you don't have it, then you cannot sync from that point on.
An alternative is to shutdown the node, copy over the database folder to the second node and then start both again.

**Comment by MLStoltzenburg** [comment]
Hallo @alexsporn!

Es funktioniert jetzt!
Vielen Dank! :-)
