### ISSUE TITLE
`NodeConfiguration` should add a `tangle_index` to prevent race conditions

### ISSUE THREAD

**Issue by grtlr** [gohornet/hornet#1623]
**Is your feature request related to a problem? Please describe.**

There is no way of knowing for which `tangle_index` the current `NodeConfiguration` was valid, which can lead to race conditions in clients.

**Describe the solution you'd like**

Add a `tangle_index` field to `NodeConfiguration`, similar to how we have a `ledger_index` for `OutputResponse`.

**Comment by muXxer** [comment]
You are talking about INX interface, right?

**Comment by grtlr** [comment]
Yeah, I think this can be closed now that we have the `ReadProtocolParameters(MilestoneRequest)` call.
