### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by sergeinnocent** [gohornet/hornet#1626]
root@maah:/opt# git clone -b production --single-branch https://github.com/iotaledger/hornet.git
Cloning into 'hornet'...
.....
Resolving deltas: 100% (14394/14394), done.
root@maah:/opt# cd hornet/
root@maah:/opt/hornet# go build
......
**build github.com/gohornet/hornet: cannot load io/fs: malformed module path "io/fs": missing dot in first path element**

**Comment by alexsporn** [comment]
which go version are you using? on which platform?

**Comment by sergeinnocent** [comment]
go version go1.13.8 linux/amd64

On Ubuntu 20.04.4 LTS

**Comment by alexsporn** [comment]
go 1.13? That is EOL since almost 2 years. Or did you mean to say go 1.18.3?
If still using go 1.13, please update to 1.18 and try again.

**Comment by alexsporn** [comment]
Closing this issue.
