### ISSUE TITLE
Posting Tagged Data Payload without protocolVersion fails 

### ISSUE THREAD

**Issue by Thoralf-M** [gohornet/hornet#1641]
**Describe the bug**
Posting the `Minimal Block with Tagged Data Payload` example from https://editor.swagger.io/?url=https://raw.githubusercontent.com/iotaledger/tips/stardust-api/tips/TIP-0025/core-rest-api.yaml for `/api/core/v2/blocks` fails with
`{"error":{"code":"400","message":"invalid parameter, error: invalid block, error: protocolVersion invalid: code=400, message=invalid parameter"}}`.
Adding `"protocolVersion": 2,` doesn't return this error anymore.

**To Reproduce**
Send this request
```bash
curl -X POST https://api.testnet.shimmer.network/api/core/v2/blocks -H 'Content-Type: application/json' -d '{
  "payload": {
    "type": 5,
    "tag": "0x68656c6c6f20776f726c64",
    "data": "0x5370616d6d696e6720646174612e0a436f756e743a203037323935320a54696d657374616d703a20323032312d30322d31315431303a32333a34392b30313a30300a54697073656c656374696f6e3a203934c2b573"
  }
}'
````

**Expected behavior**
It should work (or with the URL in my example return `{"error":{"code":"400","message":"invalid parameter, error: no parents given and node PoW is disabled: invalid block: code=400, message=invalid parameter"}}` instead)

**Comment by oopsmonk** [comment]
according to [TIP-0024](https://github.com/Wollac/protocol-rfcs/blob/tangle-message-data/tips/TIP-0024/tip-0024.md#serialized-layout) a block should include protocol version, parents, payload, and nonce.

**Comment by Thoralf-M** [comment]
Yes the final block needs to have the fields, but afaik posting just the payload should also work and the node will add the other fields (when remote PoW is enabled)

**Comment by Thoralf-M** [comment]
TIP-25 Node Core REST API was outdated and wrong
