### ISSUE TITLE
Verify genesis snapshot with community members

### ISSUE THREAD

**Issue by luca-moser** [gohornet/hornet#1683]

**Comment by muXxer** [comment]
- Scripts for generating global snapshot are finished
- Writing docs for instructions how to verify are missing

**Comment by alexsporn** [comment]
Are you doing a PR here with those? https://github.com/iotaledger/global-snapshots

**Comment by muXxer** [comment]
SoonTM

We need to wait until the next beta release, otherwise the snapshot order fix is not in place.
