### ISSUE TITLE
Investigate block processor overflow when inx-mqtt is enabled

### ISSUE THREAD

**Issue by luca-moser** [gohornet/hornet#1687]
- Check whether the QoS in the MQTT could cause a slow client to apply back pressure to the block processor

**Comment by alexsporn** [comment]
This issue arises when a slow MQTT client slows down the broker.
See https://github.com/mochi-co/mqtt/issues/95

I tested and proposed a workaround there. Let's see what the author thinks.

**Comment by alexsporn** [comment]
Switching to a fork until the upstream MQTT broker has a proper fix in place.
