### ISSUE TITLE
Test API shutdown when a new protocol version is detected

### ISSUE THREAD

**Issue by luca-moser** [gohornet/hornet#1688]
Check out what happens if a 2.0.0 node receives an announcement for new protocol versions which it doesn't support.

Expected behaviour:
- The part of the API writing of the Tangle becomes unavailable
- The node sees the new protocol version and it is available in the /info endpoint
- The nodes in the network shouldn't crash

**Comment by alexsporn** [comment]
* Configured the private tangle COO to issue a protocol version 3 upgrade announcement at milestone 10 in the milestone 5 payload
* At milestone 5 the info endpoint of the node started announcing it:
```json
"pendingProtocolParameters": [
    {
      "type": 1,
      "targetMilestoneIndex": 10,
      "protocolVersion": 3,
      "params": "0xffffffff"
    }
  ],
```
* Nodes do not accept any more blocks over the API:
```
service unavailable: url http://localhost:14265/api/core/v2/blocks, error message: Service Unavailable, error: node does not support the upcoming protocol upgrade: code=503, message=Service Unavailable
```
* Nodes are not crashing
* At milestone 10 the COO tries to issue a block with protocol version 3 and the node does not accept it, so the coo shuts down:
```
2022-08-18T17:27:37+02:00       WARN    Shutdown        Critical App self-shutdown: coordinator plugin hit a critical error: failed to send milestone: rpc error: code = Unknown desc = block has invalid protocol version 3 instead of 2: invalid block; waiting (max 300 seconds) to finish processing ...
```

@luca-moser @muXxer should I try to adapt one hornet to accept version 3 and gossip blocks with version 3?

**Comment by muXxer** [comment]
Nice, works as intended I would say :tada: 

You mean the coo hornet node?

**Comment by alexsporn** [comment]
> You mean the coo hornet node?

Yes, should I try to make the coo hornet node aware of protocol version 3 and see what happens if it gossips blocks with version 3?

**Comment by muXxer** [comment]
If that is not too complicated? :dancers:

**Comment by luca-moser** [comment]
Great! 

> should I try to adapt one hornet to accept version 3 and gossip blocks with version 3?

For the case you described, this should result in all other nodes disconnecting from the coo node. I would say it is worth giving it a try.

**Comment by alexsporn** [comment]
After discussing how the nodes should handle the protocol upgrade this ticket is done. Further details in a new ticket describing the behavior to implement.
