### ISSUE TITLE
Adding key gives deprecated warning

### ISSUE THREAD

**Issue by JannemanDev** [gohornet/hornet#1755]
If you follow step #1 from https://wiki.iota.org/hornet/how_tos/hornet_apt_repository
it gives you a deprecated warning when adding the key: https://discord.com/channels/397872799483428865/630794683920154676/1019873296088563762

Reason behind this and fix see https://itsfoss.com/apt-key-deprecated/

The step in the WIKI should be updated accordingly.

**Comment by muXxer** [comment]
thanks for the feedback.
its deprecated in your linux distribution.
that might be different for older LTS versions.

we will remove the apt setup anyway with the stardust release on mainnet, so I guess its fine for now.
if you still want to change it, feel free to create a Pull Request against the `production` branch with changes in `documentation/docs/how_tos/hornet_apt_repository.md` :+1:
