### ISSUE TITLE
package io/fs is not in GOROOT

### ISSUE THREAD

**Issue by arne-fuchs** [gohornet/hornet#1786]
**Describe the bug**
I was trying to build hornet with
`go build`
and
`./scripts/build_hornet_rocksdb_builtin.sh`
and got the following error:
`pkg/utils/io.go:7:2: package io/fs is not in GOROOT (/usr/lib/go-1.15/src/io/fs)`

**To Reproduce**
- Use fresh installation of Debian 11 Stable
- Install golang through apt (`sudo apt install golang`)
- See error

**Environment information:**
 - OS: [Debian 11 Stable]
 - RAM: [32 GB]
 - Cores: [8 Cores]
 - Type: [PC]
 - HORNET version [Production]

**Comment by muXxer** [comment]
you are using an outdated version of go.
please update to at least 1.18
