### ISSUE TITLE
IOTA Explorer Config Scripts & Wasp Nodes Deployment on Private Tangle

### ISSUE THREAD

**Issue by akov800** [gohornet/hornet#1876]
Good morning! I am currently deploying a private Stardust-based tangle using the scripts provided on this repository. I would like to ask for some instructions on how to properly set the config network files for the IOTA Explorer feature on this private network, since the `"protocolVersion":"stardust"` and the network type I guess would be `"network":"shimmer"`. 
On the other hand, following the default Tangle deployment, the provider would be the URL for the API REST port of the hornet_1 node `"provider":"http://172.18.211.11:14265"`. However, I have no idea on how to define the field for the `"feedEndpoint"`, and it would be very nice if someone could help me with some tips.

In addition, I would like to ask for some instructions on how to deploy Wasp nodes on the private Tangle so that I can start developing IOTA Smart Contracts on it.

Thanks in advance!

**Comment by Dr-Electron** [comment]
If you need support you should ask on our [Discord](https://discord.iota.org/) or [Stack Exchange](https://iota.stackexchange.com/)
