### ISSUE TITLE
Raspberry Pi 4 binary appears not executable

### ISSUE THREAD

**Issue by corbo** [gohornet/hornet#514]
The instruction to run Hornet: "./hornet -c config"  resulted in the error message 
"cannot run binary file Wrong executable file" on a Raspberry Pi 4

**To Reproduce**
These are the steps I took:
* Started with a fresh Raspbian desktop image (tried both the current Raspberry Pi OS released 2020-05-27 as well as an older 2020-02-13 version)
* Downloaded HORNET-0.4.0_Linux_ARM64.tar.gz
* Unpacked the archive which resulted in the hornet file and json files dated June 5th 16:02

**Environment information:**
 - OS: Raspbian GNU/Linux 10 (buster)
 - RAM: 2 GB
 - Cores: 4 Cores
 - Type: Raspberry Pi 4 model B rev 1.1

**Comment by IoTMOD** [comment]
Please make sure you are running a 64 bit OS (`uname -a`) 
We no longer support 32 bit architectures.

I recommended to use Ubuntu 20.04 64 bit for Raspberry Pi (https://ubuntu.com/download/raspberry-pi)
