### ISSUE TITLE
Make max. inbound and outbound peers configurable in config.json / peering.json

### ISSUE THREAD

**Issue by Travetown** [gohornet/hornet#635]
At the moment the maximum number of autopeered neighbors is limited to 4. This limitation was originally introduced to keep more nodes synchronized during spam tests.

I think it would be better this could be configured in the config.json / peering.json, since then every node owner would be able to adjust this parameter depending on the performance of his node.
This would make the entire network a bit more flexible and powerful nodes could contribute more to stability.

**Comment by muXxer** [comment]
We talked about this already.
You can change it in the config if you add the parameters. We did not add them on purpose, because people will choose way to high values, what will be bad for the network and their nodes.
